kind: PersistentVolume
apiVersion: v1
metadata:
  name: plex-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/hosthome/aldo/share/data"
